joint_state_estimator:
  ros__parameters:
    update_rate: 20.0
    reference_frame: arm_base_link
    max_velocity: 1.05
    ema_alpha: 0.4
    accel_weight: 0.3
    zero_offsets: [-1.406606, -1.326156, -2.355947, 0.000000]
    accel_zero_offset: 1.701922
    body_pitch_zero: 2.009094
